apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kc-visit-counter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EvaristoGZ/GitHubActions-ArgoCD-lab.git
    targetRevision: main
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: kc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
