apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-visit-counter
  namespace: kc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kc-visit-counter
  template:
    metadata:
      labels:
        app: kc-visit-counter
    spec:
      containers:
        - name: kc-visit-counter
          image: ghcr.io/evaristogz/githubactions-argocd-lab/kc-visit-counter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "prod"
            - name: DATABASE_URL
              valueFrom:
              secretKeyRef:
                name: db-conn
                key: url
            - name: PORT
              value: "5000"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
