apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: kc
data:
  01_create_table_visitas.sql: |
    CREATE TABLE IF NOT EXISTS visitas (
      id SERIAL PRIMARY KEY,
      fecha_hora TIMESTAMP NOT NULL DEFAULT NOW()
    );