apiVersion: v1
kind: Secret
metadata:
  name: secrets-db
  namespace: kc
type: Opaque
stringData:
  # Individual credentials. You need to set these environment variables in app.py
  DB_HOST: "postgres.kc.svc.cluster.local"
  DB_NAME: "basedatos"
  DB_USER: "usuario"
  DB_PASSWORD: "contrasenya"
  DB_PORT: "5432"
  # Recreate full URL for applications that need it
  DATABASE_URL: "postgresql://usuario:contrasenya@postgres.kc.svc.cluster.local:5432/basedatos"
