apiVersion: v1
kind: Service
metadata:
  name: kc-visit-counter
  namespace: kc
spec:
  type: ClusterIP
  selector:
    app: kc-visit-counter
  ports:
    - name: http
      port: 80
      targetPort: 5000
